# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_remove_user_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id_number',
        ),
    ]
