# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_authuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='player',
            name='nick_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
