# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_auto_20160419_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castle', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('attack_skill', models.IntegerField()),
                ('defense_skill', models.IntegerField()),
                ('minimum_melee_damage', models.IntegerField()),
                ('maximum_melee_damage', models.IntegerField()),
                ('minimum_range_damage', models.IntegerField()),
                ('maximum_range_damage', models.IntegerField()),
                ('health', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('growth', models.IntegerField()),
                ('special', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='attributes',
            field=models.CharField(default=set([0]), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='//source//', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.CharField(default=set([0]), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='special',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='spells',
            field=models.CharField(default=set([0]), max_length=255),
            preserve_default=False,
        ),
    ]
