# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_auto_20160420_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=10)),
                ('creator_pk', models.IntegerField()),
                ('guest_pk', models.IntegerField()),
                ('creator_castle', models.CharField(max_length=20)),
                ('guest_castle', models.CharField(max_length=20)),
                ('growth', models.IntegerField()),
                ('all_units_stats', models.CharField(max_length=255)),
            ],
        ),
    ]
