# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0008_auto_20160421_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='guest_pk',
            field=models.CharField(max_length=255),
        ),
    ]
