# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-26 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_auto_20160421_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='picture',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
