# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-26 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0010_unit_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='picture',
        ),
    ]
