# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-26 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0011_remove_unit_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='units',
            field=models.CharField(max_length=1000),
        ),
    ]
