# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0012_auto_20160426_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='units',
            field=models.CharField(max_length=2000),
        ),
    ]
