# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-01 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0014_auto_20160427_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='maximum_melee_damage',
            new_name='maximum_damage',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='minimum_melee_damage',
            new_name='minimum_damage',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='maximum_range_damage',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='minimum_range_damage',
        ),
    ]
