# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0015_auto_20160501_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='log',
            field=models.CharField(default=1, max_length=20000),
            preserve_default=False,
        ),
    ]
