# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0017_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
