# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0018_spell_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
