# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0019_spell_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='cells_formula',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
