# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0020_spell_cells_formula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='cells_formula',
            new_name='cells',
        ),
    ]
