# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0021_auto_20160507_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='creator_current_mp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='creator_spell',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='guest_current_mp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='guest_spell',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
